# Generated by Django 4.2.5 on 2023-09-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ingredient_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='app.category'),
        ),
    ]
